---
- hosts: all
  vars_files: 
    - ansible_playbook.yml
  user: ansible
  become: True
  tasks:
    - name: Install NTP
      yum:
        pkg: ntp
        state: installed
    
    - name: Start NTP
      command: service ntpd start

    - name: Start NTP on boot
      command: systemctl enable ntpd

    - name: Stop firewalld/iptables
      command: service firewalld stop

    - name: Disable SElinux permanetly
      lineinfile: dest=/etc/sysconfig/selinux state=present create=no regexp='SELINUX=.*' line='SELINUX=disabled'
    
    - name: Disable selinux
      selinux:
        state: disabled

    - name: Create hostname entry to 
      lineinfile: dest=/etc/hostname state=present create=yes regexp='.*' line='{{hostname}}'

    - name: Set networking yes
      lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='NETWORKING=.*' line='NETWORKING=yes'

    - name: Set hostname to {{hostname}}
      lineinfile: dest=/etc/sysconfig/network create=yes state=present regexp='HOSTNAME=.*' line='HOSTNAME={{hostname}}'

    - name: Create Ambari Repo
      command: wget http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.2.0/ambari.repo -O /etc/yum.repos.d/ambari.repo

    - name: Clean YUM
      command: yum clean all

    - name: Install Ambari Agent
      yum:
        pkg: ambari-agent
        state: installed

    - name: Configure Ambari agent to register at Ambari server
      lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini create=no state=present regexp='hostname=.*' line='hostname={{hostname}}'

    - name: Update Ambari Agent INI file
      command: sed -i '/credential_shell_cmd/a force_https_protocol=PROTOCOL_TLSv1_2' /etc/ambari-agent/conf/ambari-agent.ini

- hosts: ambari-server
  user: ansible
  become: True
  tasks: 
    - name: Install Ambari server
      yum:
        pkg: ambari-server
        state: installed

    - name: Configure Ambari server
      command: ambari-server setup -s

    - name: Sleep
      command: sleep 10
      
    - name: Start Ambari server
      command: ambari-server restart
    
- hosts: ambari-agents
  user: ansible
  become: True
  tasks: 
    - name: Start Ambari agent
      command: ambari-agent restart
